version: "3.6"
services:
    envoy:
      image: envoyproxy/envoy:latest
      container_name: envoy
      volumes:
        - /Users/ckd/ZZH/Projects/GoProjects/grpc-login/envoy:/etc/envoy
      ports:
        - "8080:8080"
        - "9901:9901"
        - "10000:10000"